### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/breakfast#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by Latsalomao** [comment]
Cheers from Morelia!

**Comment by beardofedu** [comment]
👋 **hello!** , good morning 🧇

**Comment by vmcherukuri** [comment]
Hello Matt!

**Comment by czammar** [comment]
Hello guys 👍

**Comment by dyousef-k** [comment]
Good morning.

**Comment by ricardoauribe** [comment]
🎧 Hi!

**Comment by aslater3** [comment]
Morning 💯 glad to be here  😃

**Comment by Pilo1961** [comment]
Hello Matt

**Comment by harshdeep83** [comment]
Hello everyone

**Comment by krysmyth-ksmith02** [comment]
hello!

**Comment by patatwork365** [comment]
Good afternoon 🎏

**Comment by gsuzor91** [comment]
Good morning.

**Comment by e-mrazek** [comment]
Hello

**Comment by mjksscb4** [comment]
Good afternoon

**Comment by vikram-ganti** [comment]
👋

**Comment by kzoo-akerman** [comment]
Hello

**Comment by pranav0903** [comment]
Hello everyone!

**Comment by kshitishwars** [comment]
Hello Matt,
Good Morning.

**Comment by kaswba** [comment]
Hello

**Comment by pranav0903** [comment]
👋

**Comment by olizardo47** [comment]
ASD

**Comment by sachingupta0409** [comment]
Hi

**Comment by mjksscb4** [comment]
Hi

**Comment by mikechappelow** [comment]
hi

**Comment by uskaxg74** [comment]
Test comment.
